name: Subgraph unit tests
on: [push]

concurrency:
  group: ${{ github.ref }}-subgraph
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build subgraph
        run: nix develop -c subgraph-run-build

      - name: Matchstick tests
        run: nix develop -c subgraph-run-test