name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        run: nix develop --command npm test
